pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

rootProject.name = 'reto-tecnico'

include ':app-service'
include ':model'
include ':usecase'
project(':app-service').projectDir = file('./applications/app-service')
project(':model').projectDir = file('./domain/model')
project(':usecase').projectDir = file('./domain/usecase')
include ':r2dbc'
project(':r2dbc').projectDir = file('./infrastructure/driven-adapters/r2dbc')
include ':reactive-web'
project(':reactive-web').projectDir = file('./infrastructure/entry-points/reactive-web')
include ':validator'
project(':validator').projectDir = file('./infrastructure/helpers/validator')
include ':sqs-sender'
project(':sqs-sender').projectDir = file('./infrastructure/driven-adapters/sqs-sender')